---
# curl -D - -s -o /dev/null 
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: nginx install prerequirements
  hosts: all
  become: yes
  vars:
    a: "tls.693823654b8d63866ad8d62652c05e65.kis.im"
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        pkg:
        - nginx
        - curl
        - letsencrypt
    - name: create www folder
      file:
        path: /opt/www/acme
        state: directory
        recurse: yes
    - name: delete default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: copy config
      template:
        src: files/rebrain-0.conf.j2
        dest: /etc/nginx/sites-enabled/rebrain.conf
    - name: create challange folder
      file:
        path: /opt/www/acme/.well-known/acme-challenge
        state: directory
        recurse: yes
    - name: restat nginx
      service:
        name: nginx
        state: restarted
    - name: exec letsencrypt
      command: letsencrypt certonly --non-interactive --agree-tos -m webmaster@mail.ru --webroot -w /opt/www/acme/ -d {{ a }}
    - name: copy config
      template:
        src: files/rebrain-1.conf.j2
        dest: /etc/nginx/sites-enabled/rebrain.conf
    - name: create ssl folder
      file:
        path: /etc/nginx/ssl
        state: directory
        owner: root
        group: root
        mode: '0600'
    - name: create pass ca key
      command: openssl genrsa -aes256 -passout pass:12345678 -out ca.pass.key 4096
    - name: create ca key
      command: openssl rsa -passin pass:12345678 -in ca.pass.key -out ca.key
    - name: create ca
      command: openssl req -new -x509 -days 3650 -key ca.key -out ca.crt -subj "/C=RU/L=Moscow/O=Rebrain/CN=CA"
    - name: create cliert pass key
      command: openssl genrsa -aes256 -passout pass:87654321 -out client.pass.key 4096
    - name: create client key
      command: openssl rsa -passin pass:87654321 -in client.pass.key -out client.key
    - name: create client csr
      command: openssl req -new -key client.key -out client.csr -subj "/C=RU/L=Moscow/O=Rebrain/CN=Client"
    - name: create client cert
      command: openssl x509 -req -days 3650 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 1 -out client.crt
    - name: copy ca to nginx
      copy:
        remote_src: yes
        src: ca.crt
        dest: /etc/nginx/ssl/
    - name: restat nginx
      service:
        name: nginx
        state: restarted
    - name: creta folder for auto checker
      file:
        path: /opt/ssl
        state: directory
    - name: copy files to auto checker
      copy:
        remote_src: yes
        src: '{{ item }}'
        dest: /opt/ssl/
      with_items:
        - ca.crt
        - ca.key
        - client.crt
        - client.key
    - name: restart service
      service:
        name: nginx
        state: restarted
