---
# curl -D - -s -o /dev/null 
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: nginx install prerequirements
  hosts: all
  become: yes
  vars:
    a: "files.9e74a07f43cb5e3ebd022a64506f0b47.kis.im"
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        pkg:
        - nginx
        - curl
    - name: create folder
      file:
        path: /opt/www/{{ a }}
        state: directory
        recurse: yes
    - name: create file test1.html
      lineinfile:
        path: /opt/www/{{ a }}/test1.html
        line: test1
        create: yes
    - name: create file test2.html
      lineinfile:
        path: /opt/www/{{ a }}/test2.html
        line: test2
        create: yes
    - name: create file test3.html
      lineinfile:
        path: /tmp/test3.html
        line: test3
        create: yes
    - name: delete default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: copy config
      template:
        src: files/rebrain.conf.j2
        dest: /etc/nginx/sites-enabled/rebrain.conf
    - name: restat nginx
      service:
        name: nginx
        state: restarted
