---
# curl -D - -s -o /dev/null 
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: nginx install prerequirements
  hosts: all
  become: yes
  vars:
    a: "tls.693823654b8d63866ad8d62652c05e65.kis.im"
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        pkg:
        - nginx
        - curl
        - letsencrypt
    - name: create www folder
      file:
        path: /opt/www/acme
        state: directory
        recurse: yes
    - name: delete default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: copy config
      template:
        src: files/rebrain.conf.j2
        dest: /etc/nginx/sites-enabled/rebrain.conf
    - name: restat nginx
      service:
        name: nginx
        state: restarted
    - name: exec letsencrypt
      command: letsencrypt certonly --non-interactive --agree-tos -m webmaster@example.com --webroot -w /opt/www/acme/ -d {{ a }}
