---
# curl -D - -s -o /dev/null 
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: nginx install prerequirements
  hosts: all
  become: yes
  vars:
    a: "auth.98fc4eb77aa2bdeb2fe264ee97e23997.kis.im"
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        pkg:
        - nginx
        - curl
        - python3-pip
    - name: install passlib
      pip:
        name:
        - passlib 
    - name: delete default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: create htpawwd file
      htpasswd:
        path: /etc/nginx/passwdfile
        name: user
        password: 'test'
    - name: copy config
      template:
        src: files/rebrain.conf.j2
        dest: /etc/nginx/sites-enabled/rebrain.conf
    - name: restat nginx
      service:
        name: nginx
        state: restarted
