---
# curl -D - -s -o /dev/null 
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: nginx install prerequirements
  hosts: all
  become: yes
  vars:
    a: "alpha.0993145134e20721779b089941cf40c9.kis.im"
    b: "beta.0993145134e20721779b089941cf40c9.kis.im"
    c: "gamma.0993145134e20721779b089941cf40c9.kis.im"
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: install prerequirements
      apt:
        pkg:
        - curl
        - gnupg2
        - ca-certificates
        - lsb-release
        - ubuntu-keyring
    - name: install key
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present
        keyring: /usr/share/keyrings/nginx-archive-keyring.gpg
    - name: get release
      command: lsb_release -cs
      register: release
    - name: add repo
      lineinfile:
        path: /etc/apt/sources.list.d/nginx.list
        line: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/mainline/ubuntu {{ release.stdout }} nginx"
        create: yes
    - name: set pin priority
      lineinfile:
        path: /etc/apt/preferences.d/99nginx
        line: "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n"
        create: yes
    - name: apt update
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        pkg:
        - nginx
    - name: set max workers
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: "^.*worker_processes.*"
        line: "worker_processes    4;"
    - name: set worker connections
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: "^.*worker_connections.*"
        line: "    worker_connections    2048;"
    - name: set client max body size
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: ".*sendfile.*on.*"
        line: "    client_max_body_size    50m;"
    - name: copy config
      template:
        src: files/rebrain.conf.j2
        dest: /etc/nginx/conf.d/rebrain.conf
    - name: restat nginx
      service:
        name: nginx
        state: restarted
