---
# curl -D - -s -o /dev/null 
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: nginx install prerequirements
  hosts: all
  become: yes
  vars:
    a: "backend.edec310a0198886efe093707e1943259.kis.im"
  tasks:
    - name: enable sources
      shell: sed -i 's/# deb-src/deb-src/g' /etc/apt/sources.list
    - name: apt update
      apt:
        update_cache: yes
        pkg:
        - nginx
        state: build-dep
    - name: install requirements
      apt:
        pkg:
        - curl
        - gcc
        - fakeroot
        - geoipupdate
    - name: get sources
      shell: apt-get source nginx
      args:
        chdir: /opt
    - name: clone nginx_upstream_check_module repo
      git:
        repo: https://github.com/yaoweibin/nginx_upstream_check_module
        dest: /opt/nginx_upstream_check_module
        clone: yes
        update: yes
    - name: clone geoip2 repo
      git:
        repo: https://github.com/leev/ngx_http_geoip2_module.git
        dest: /opt/ngx_http_geoip2_module
        clone: yes
        update: yes
    - name: patch
      patch:
        src: /opt/nginx_upstream_check_module/check_1.16.1+.patch
        basedir: /opt/nginx-1.18.0
        strip: 1
        remote_src: yes  
    - name: copy rules
      copy:
        src: rules
        dest: /opt/nginx-1.18.0/debian/rules
    - name: build
      shell:
        cmd: dpkg-buildpackage -b --no-sign
        chdir: /opt/nginx-1.18.0
    - name: install common
      shell:
        cmd: dpkg -i /opt/nginx-common_1.18.0-0ubuntu1.2_all.deb
    - name:  install mods
      shell:
        cmd: dpkg -i /opt/libnginx-mod-*
    - name: install core
      shell:
        cmd: dpkg -i /opt/nginx-core_1.18.0-0ubuntu1.2_amd64.deb
    - name: copy dynamic module
      copy:
        src: /opt/nginx-1.18.0/debian/build-core/objs/ngx_http_geoip2_module.so
        dest: /usr/lib/nginx/modules/
        remote_src: yes
    - name: copy GeoIP.conf file
      copy:
        src: GeoIP.conf
        dest: /etc/GeoIP.conf
    - name: update GeoIP
      shell:
        cmd: geoipupdate
    - name: cony nginx.conf
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: delete default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: copy config
      template:
        src: files/rebrain.conf.j2
        dest: /etc/nginx/sites-enabled/rebrain.conf
    - name: restat nginx
      service:
        name: nginx
        state: restarted
