---
# curl -D - -s -o /dev/null 
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: nginx install prerequirements
  hosts: all
  become: yes
  vars:
    a: "log.92c7ed2130be321aac1d04006668e884.kis.im"
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        pkg:
        - nginx
        - curl
    - name: delete default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: copy config
      template:
        src: files/rebrain.conf.j2
        dest: /etc/nginx/sites-enabled/rebrain.conf
    - name: restat nginx
      service:
        name: nginx
        state: restarted
    - name: download exporter
      uri:
        url: https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.8.0/prometheus-nginxlog-exporter_1.8.0_linux_amd64.deb
        dest: ./prometheus-nginxlog-exporter_1.8.0_linux_amd64.deb
        creates: ./prometheus-nginxlog-exporter_1.8.0_linux_amd64.deb
    - name: install exporter
      apt:
        deb: ./prometheus-nginxlog-exporter_1.8.0_linux_amd64.deb
    - name: copy exporter config
      template:
        src: files/prometheus-nginxlog-exporter.hcl.j2
        dest: /etc/prometheus-nginxlog-exporter.hcl
    - name: start exporter service
      service:
        name: prometheus-nginxlog-exporter
        state: restarted
